Update to latest official copy

diff --git a/utils/env b/utils/env
--- a/utils/env
+++ b/utils/env
@@ -18,13 +18,8 @@ importutility system
 export ENV_CONFIG_FILENAME=".newton-env-config"
 
 function env.getnumber() {
-  local hostNum=$(env.getproperty HOST_PROPERTIES_ENVNUM)
-  if string.isnotemptyorblank "$hostNum"
-  then
-    echo "$hostNum"
-  else
-    echo "0"
-  fi
+  local envNum=$(env.getproperty HOST_PROPERTIES_ENVNUM "0")
+  echo "$envNum"
 }
 
 # Write a variable specific to this environment.
@@ -40,28 +35,35 @@ function env.getnumber() {
 # file extension to avoid variable name conflicts
 function env.writevartodisk() {
   local varName="$1"
-  local extension
-  extension=$(env.getnumber)
-  system.writevartodisk "$varName" "$extension"
+  local value="${!varName}"
+  env.setproperty "$varName" "$value"
 }
 
 # Write a variable specific to this environment.
 # Pass the *name* of the variable only, not its
 # value with "$".
+# Pass a default value as the second argument.
 # e.g.:
-# myvar=$(env.readvarfromdisk myvar)
+# myvar=$(env.readvarfromdisk myvar defaultValue)
 function env.readvarfromdisk() {
   local varName="$1"
-  local extension
-  extension=$(env.getnumber)
-  system.readvarfromdisk "$varName" "$extension"
+  local defaultValue="$2"
+  local value=$(env.getproperty "$varName")
+  if string.isemptyorblank "$value"
+  then
+    echo "$defaultValue"
+    return 1
+  else
+    echo "$value"
+    return 0
+  fi
 }
 
+# Pass the *name* of the variable only, not its
+# value with "$".
 function env.removevarfromdisk() {
-  local varName="$1"
-  local extension
-  extension=$(env.getnumber)
-  system.removevarfromdisk "$varName" "$extension"
+  env.deleteproperty "$1"
+  return $?
 }
 
 function env.isInitialized() {
@@ -75,16 +77,17 @@ function env.isInitialized() {
   fi
 }
 
-function env.getconfigpath() {
-  echo "$ENV_CONFIG_ROOT_PATH/env$(env.getnumber)"
-}
 
+# Call like env.getproperty "<propertyname>" "[<default-value>]"
+# Pass a second optional argument as the default value to echo when the
+# property is not found (but return value will be 1, or FALSE)
 function env.getproperty() {
   local propertyname="$1"
+  local defaultvalue="${2:-}"
 
   if string.isemptyorblank "$propertyname"
   then
-    echo ""
+    echo "$defaultvalue"
     return 1
   fi
 
@@ -104,19 +107,20 @@ function env.getproperty() {
   # If we still can't figure out the newtonPath, exit
   if string.isemptyorblank "$newtonPath"
   then
-    echo ""
+    echo "$defaultvalue"
     return 1
   fi
 
   local pathsToCheck=(
     "$newtonPath/.build_config"
     "$newtonPath/buildSrc/tools/config/versions.bash"
+    "$newtonPath/$ENV_CONFIG_FILENAME"
   )
 
   local value=""
   for filePath in "${pathsToCheck[@]}"
   do
-    value=$(system.getkeyvaluefromfile "$filePath" "$propertyname" --silent)
+    value="$(system.getkeyvaluefromfile "$filePath" "$propertyname")"
     if ! string.isemptyorblank "$value"
     then
       echo "$value"
@@ -125,8 +129,67 @@ function env.getproperty() {
   done
 
   # Didn't find the key anywhere.
-  echo ""
+  echo "$defaultvalue"
   return 1
+}
+
+function env.setproperty() {
+  local propertyname="$1"
+  local propertyvalue="$2"
+
+  if string.isemptyorblank "$propertyname"
+  then
+    echo "Usage: env.setproperty <propertyname> <propertyvalue>" >&2
+    return 1
+  fi
+
+  local newtonPath="$REPO_NEWTON"
+  if string.isemptyorblank "$newtonPath"
+  then
+    newtonPath=$(string.extractByRegex "$(pwd)" "/.*/newton[0-9]*")
+  fi
+
+  # If we still can't figure out the newtonPath, exit
+  if string.isemptyorblank "$newtonPath"
+  then
+    echo "Error: Cannot determine newton path" >&2
+    return 1
+  fi
+
+  local configFilePath="$newtonPath/$ENV_CONFIG_FILENAME"
+  system.setkeyvalueinfile "$configFilePath" "$propertyname" "$propertyvalue"
+  return $?
+}
+
+function env.deleteproperty() {
+  local propertyname="$1"
+
+  if string.isemptyorblank "$propertyname"
+  then
+    echo "Usage: env.deleteproperty <propertyname>" >&2
+    return 1
+  fi
+
+  local newtonPath="$REPO_NEWTON"
+  if string.isemptyorblank "$newtonPath"
+  then
+    newtonPath=$(string.extractByRegex "$(pwd)" "/.*/newton[0-9]*")
+  fi
+
+  # If we still can't figure out the newtonPath, exit
+  if string.isemptyorblank "$newtonPath"
+  then
+    echo "Error: Cannot determine newton path" >&2
+    return 1
+  fi
+
+  local configFilePath="$newtonPath/$ENV_CONFIG_FILENAME"
+  system.deletekeyvaluefromfile "$configFilePath" "$propertyname" --silent
+  return $?
+}
+
+function env.refresh() {
+  mongoDropAll; mongoDropToProduction; cleanMost; buildall
 }
 
 
diff --git a/utils/git b/utils/git
--- a/utils/git
+++ b/utils/git
@@ -214,6 +214,12 @@ function git.patchlatestcommit() {
 
 # Creates a patch for the specified commit in your branch
 function git.patchcommit() {
+  if ! git.isinagitrepo
+  then
+    print_error "Not in a git repository"
+    return 1
+  fi
+
   # Commit SHA1 id sent as argument. -1 tells git to patch only the last 1 commit.
   local commitId=$1
 
@@ -395,6 +401,12 @@ function git.getbasebranchname() {
 
 # Create a patch of uncommitted changes with *LOCAL* HEAD
 function git.patchuncommittedchanges() {
+  if ! git.isinagitrepo
+  then
+    print_error "Not in a git repository"
+    return 1
+  fi
+
   local message="$1"
   local optionalFlag="$2"
   local path=$(git.getpatchfilepath "$message" "$optionalFlag")
@@ -409,6 +421,12 @@ function git.patchuncommittedchanges() {
 # and compare with the remote origin master / lsb/master
 # *** CAUTION ToDo: Doesn't handle new files as of now. ***
 function git.patchallchanges() {
+  if ! git.isinagitrepo
+  then
+    print_error "Not in a git repository"
+    return 1
+  fi
+
   echo "Refreshing tags..."
   git fetch origin --tags --force --prune
   local path=$(git.getpatchfilepath "$@")
@@ -420,12 +438,24 @@ function git.patchallchanges() {
 # Applies a patch and creates .rej files for the changes
 # that it could not apply.
 function git.applypatch() {
+  if ! git.isinagitrepo
+  then
+    print_error "Not in a git repository"
+    return 1
+  fi
+
   git apply --reject --whitespace=fix "$1" # patch file path
 }
 
 # Pass the upstream branch name, followed by remoteName if
 # other than "origin"
 function git.setupstream() {
+  if ! git.isinagitrepo
+  then
+    print_error "Not in a git repository"
+    return 1
+  fi
+
   local branchNameToPush="$1"
   local remoteName="$2"
 
@@ -444,6 +474,12 @@ function git.setupstream() {
 }
 
 function git.unsetupstream() {
+  if ! git.isinagitrepo
+  then
+    print_error "Not in a git repository"
+    return 1
+  fi
+
   git branch --unset-upstream
 }
 
@@ -451,10 +487,22 @@ function git.unsetupstream() {
 # the current one. As expected, calling it twice should
 # bring you back to the same branch.
 function git.checkoutpreviousbranch() {
+  if ! git.isinagitrepo
+  then
+    print_error "Not in a git repository"
+    return 1
+  fi
+
   git checkout -
 }
 
 function git.deletecurrentbranch() {
+  if ! git.isinagitrepo
+  then
+    print_error "Not in a git repository"
+    return 1
+  fi
+
   local noConfirmationArg="$1"
   local currentbranch=$(git.getcurrentbranch)
   if string.equals "$noConfirmationArg" "--no-confirmation" || general.inputyesorno "Are you sure you want to delete the current branch ($currentbranch)"
@@ -465,6 +513,12 @@ function git.deletecurrentbranch() {
 }
 
 function git.setglobalignorefile() {
+  if ! git.isinagitrepo
+  then
+    print_error "Not in a git repository"
+    return 1
+  fi
+
   if string.isemptyorblank $1
   then
     git config --global core.excludesfile $globalgitignorefile
@@ -477,6 +531,12 @@ function git.setglobalignorefile() {
 # id of the merge commit in the given branch. Default
 # branch is master
 function git.getmergecommit() {
+  if ! git.isinagitrepo
+  then
+    print_error "Not in a git repository"
+    return 1
+  fi
+
   if string.isemptyorblank $(which git-get-merge)
   then
     echo "git-get-merge utility not found. Please install from https://github.com/jianli/git-get-merge"
@@ -487,6 +547,12 @@ function git.getmergecommit() {
 }
 
 function git.deletebranch() {
+  if ! git.isinagitrepo
+  then
+    print_error "Not in a git repository"
+    return 1
+  fi
+
   local branchToDelete="$1"
   if string.isemptyorblank "$branchToDelete" || string.equals "$(git.getcurrentbranch)" "$branchToDelete"
   then
@@ -619,9 +685,12 @@ function git.pastefileswithfolderstructure() {
   echo "Total $totalFilesSuccessfullyCopied files from $sourceDirectory have been copied to $destinationDirectory"
 }
 
-# Function to find all branches that have changed a given file
-# Written using LLM Coding agents, seems to work fine,
-# but please be careful.
+# Function to find all branches that have UNIQUE commits changing a given file.
+# "Unique" means commits that are in the branch but not in its base (origin/master).
+# This excludes inherited commits from the base branch.
+# By default searches local branches only, but can search remote branches too.
+# For remote branches, origin/master is assumed as the base.
+# For local branches, merge-base with origin/master is used.
 git.findbrancheswithfilechanges() {
     local file_path=""
     local time_limit=""
@@ -695,7 +764,9 @@ git.findbrancheswithfilechanges() {
         cat << 'EOF'
 Usage: git.findbrancheswithfilechanges [OPTIONS] <file_path>
 
-Find all branches that have changes to a specific file.
+Find all branches that have UNIQUE commits changing a specific file.
+"Unique" means commits in the branch but not in origin/master (the base).
+This excludes changes inherited from the base branch.
 
 OPTIONS:
     -f, --file FILE         File path to search for (can also be passed as positional arg)
@@ -811,16 +882,24 @@ EOF
 
         [[ "$verbose" == true ]] && echo "Checking branch $checked_count/$total_branches: $branch"
 
-        # Build git log command with time limit if specified
-        local log_cmd="git log --oneline"
-        if [[ -n "$time_limit" ]]; then
-            log_cmd="$log_cmd --since=\"$time_limit\""
+        # Determine base reference for this branch
+        # Remote branches: use origin/master as base
+        # Local branches: use merge-base with origin/master
+        local base_ref
+        if [[ "$branch" =~ ^(origin/|remotes/) ]]; then
+            base_ref="origin/master"
+        else
+            base_ref=$(git merge-base "$branch" origin/master 2>/dev/null)
         fi
-        log_cmd="$log_cmd -- \"$file_path\""
 
-        # Check if branch has commits affecting the file
+        if [[ -z "$base_ref" ]]; then
+            [[ "$verbose" == true ]] && echo "  ! Could not determine base for $branch, skipping"
+            continue
+        fi
+
+        # Check if branch has UNIQUE commits (not in base) affecting the file
         local commits
-        commits=$(git log --oneline ${time_limit:+--since="$time_limit"} "$branch" -- "$file_path" 2>/dev/null)
+        commits=$(git log --oneline ${time_limit:+--since="$time_limit"} "$base_ref..$branch" -- "$file_path" 2>/dev/null)
         local exit_code=$?
 
         if [[ $exit_code -eq 0 ]] && [[ -n "$commits" ]]; then
@@ -856,6 +935,209 @@ EOF
 }
 
 
+# Compact commit viewer shared by finder helpers
+function git.showcommit() {
+  local commit="$1"
+  if string.isemptyorblank "$commit"
+  then
+    return 1
+  fi
+
+  local commitDate commitMessage filesChanged
+  commitDate=$(git show -s --format="%cd" --date=short "$commit")
+  commitMessage=$(git show -s --format="%s" "$commit")
+  commitMessage=$(string.trim "$commitMessage")
+  commitMessage=$(string.truncate "$commitMessage" 100)
+  filesChanged=$(git show --pretty="" --name-only "$commit" | sed '/^$/d')
+
+  echo "$commit"
+  echo "  date : $commitDate"
+  echo "  Summary  : $commitMessage"
+  if string.isnotemptyorblank "$filesChanged"
+  then
+    echo "  files:"
+    echo "$filesChanged" | sed 's/^/    - /'
+  else
+    echo "  files: (none)"
+  fi
+  echo "--------------------------------------------------------------------------------"
+  echo "--------------------------------------------------------------------------------"
+
+}
+
+function git.findcommitbymessage() {
+  if ! git.isinagitrepo
+  then
+    print_error "Not in a git repository"
+    return 1
+  fi
+
+  local limit=""
+  local argCount=$#
+  if [[ $argCount -ge 2 ]]
+  then
+    local lastArg="${!argCount}"
+    if [[ "$lastArg" =~ ^[0-9]+$ ]]
+    then
+      limit="$lastArg"
+      argCount=$((argCount-1))
+      set -- "${@:1:$argCount}"
+    fi
+  fi
+
+  local search="$*"
+  if string.isemptyorblank "$search"
+  then
+    echo "Usage: git.findcommitbymessage <search string>"
+    return 1
+  fi
+
+  local commits
+  commits=$(git log -i --grep="$search" --fixed-strings --pretty=format:"%H" ${limit:+-n $limit})
+
+  if string.isemptyorblank "$commits"
+  then
+    echo "No commits found matching message: $search"
+    return 0
+  fi
+
+  echo "Commits matching message: $search"
+  if string.isnotemptyorblank "$limit"
+  then
+    echo "(showing newest $limit)"
+  fi
+  echo ""
+  echo "$commits" | while read -r commitId
+  do
+    git.showcommit "$commitId"
+  done
+}
+
+function git.findcommitbyauthor() {
+  if ! git.isinagitrepo
+  then
+    print_error "Not in a git repository"
+    return 1
+  fi
+
+  local limit=""
+  local argCount=$#
+  if [[ $argCount -ge 2 ]]
+  then
+    local lastArg="${!argCount}"
+    if [[ "$lastArg" =~ ^[0-9]+$ ]]
+    then
+      limit="$lastArg"
+      argCount=$((argCount-1))
+      set -- "${@:1:$argCount}"
+    fi
+  fi
+
+  local search="$*"
+  if string.isemptyorblank "$search"
+  then
+    echo "Usage: git.findcommitbyauthor <author substring>"
+    return 1
+  fi
+
+  local commits
+  commits=$(git log -i --author="$search" --pretty=format:"%H" ${limit:+-n $limit})
+
+  if string.isemptyorblank "$commits"
+  then
+    echo "No commits found matching author: $search"
+    return 0
+  fi
+
+  echo "Commits matching author: $search"
+  if string.isnotemptyorblank "$limit"
+  then
+    echo "(showing newest $limit)"
+  fi
+  echo ""
+  echo "$commits" | while read -r commitId
+  do
+    git.showcommit "$commitId"
+  done
+}
+
+
+
+# Helper function to determine the base reference for comparison
+function __get_base_ref() {
+    local current_branch
+    local upstream_branch
+    local default_branch
+    local base_ref
+
+    current_branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
+    if [ -z "$current_branch" ]; then
+        echo "Error: Not in a git repository" >&2
+        return 1
+    fi
+
+    # Strategy 1: Check if upstream tracking branch is set
+    upstream_branch=$(git rev-parse --abbrev-ref --symbolic-full-name @{u} 2>/dev/null)
+    if [ -n "$upstream_branch" ]; then
+        echo "$upstream_branch"
+        return 0
+    fi
+
+    # Strategy 2: Check if remote branch with same name exists
+    if git show-ref --verify --quiet "refs/remotes/origin/$current_branch"; then
+        echo "origin/$current_branch"
+        return 0
+    fi
+
+    # Strategy 3: Use merge-base with default branch
+    default_branch=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/@@')
+    if [ -z "$default_branch" ]; then
+        # Fallback: try common default branches
+        if git show-ref --verify --quiet refs/remotes/origin/master; then
+            default_branch="origin/master"
+        elif git show-ref --verify --quiet refs/remotes/origin/main; then
+            default_branch="origin/main"
+        else
+            echo "Error: Cannot determine default branch" >&2
+            return 1
+        fi
+    fi
+
+    base_ref=$(git merge-base HEAD "$default_branch" 2>/dev/null)
+    if [ -z "$base_ref" ]; then
+        echo "Error: Cannot find merge-base with $default_branch" >&2
+        return 1
+    fi
+
+    echo "$base_ref"
+    return 0
+}
+
+# Function to show commits that this branch has that are not in the base reference
+# (e.g. master or upstream tracking branch)
+function git.finduniquecommits() {
+    local base_ref
+    base_ref=$(__get_base_ref)
+    if [ $? -ne 0 ]; then
+        return 1
+    fi
+
+    # Show the commits
+    git log "$base_ref..HEAD" "$@"
+}
+
+# Lightweight function to count local commits
+function git.uniquecommitscount() {
+    local base_ref
+    base_ref=$(__get_base_ref)
+    if [ $? -ne 0 ]; then
+        return 1
+    fi
+
+    # Use rev-list --count which is more efficient than git log + wc
+    git rev-list --count "$base_ref..HEAD"
+}
+
 
 
 # Show your git branches sorted by latest commit
@@ -878,3 +1160,5 @@ alias git.findmergecommit='git.getmergecommit'
 alias git.parentcommit='git.getmergecommit'
 alias git.mergecommit='git.getmergecommit'
 alias git.createfolderstructurefromcommit='git.copyfilesincommit'
+alias git.showlocalcommits='git.finduniquecommits'
+alias git.showuniquecommits='git.finduniquecommits'
diff --git a/utils/system b/utils/system
--- a/utils/system
+++ b/utils/system
@@ -310,6 +310,17 @@ function system.killallwithname() {
   pkill -9 -f -i "$1"
 }
 
+function system.killbypid() {
+  local pid="$1"
+  if ! string.isnumber "$pid"
+  then
+    echo "Please provide a valid PID (process ID) to kill."
+    return 1
+  fi
+
+  kill -9 "$pid"
+}
+
 function system.enablelocate() {
   system.buildlocatedb
 }
@@ -377,14 +388,14 @@ function system.getlatestdownload() {
   fi
 }
 
-# Call like system.getkeyvaluefromfile "<file-path>" "<key>"
-# Pass a third argument "--silent" or "-s" to echo an empty
-# string when a file or key is not found without echoing
-# error message
+# Call like system.getkeyvaluefromfile "<file-path>" "<key>" "[<default-value>]"
+# Pass a third optional argument as the default value to echo when the
+# file or key is not found.
+# When the default value is not provided, the return value will be 1, or FALSE
 function system.getkeyvaluefromfile() {
     local file_path="$1"
     local search_key="$2"
-    local silent="$3"
+    local default_value="${3:-}"
 
     # Check if both parameters are provided
     if string.isemptyorblank "$file_path" || string.isemptyorblank "$search_key"
@@ -396,13 +407,8 @@ function system.getkeyvaluefromfile() {
     # Check if file exists and is readable
     if ! system.fileexists "$file_path"
     then
-      if string.equals $silent "--silent" || string.equals $silent "-s"
-      then
-        echo ""
-      else
-        echo "Error: File '$file_path' does not exist or is not readable" >&2
-      fi
-      return 2
+      echo "$default_value"
+      return 1
     fi
 
     # Read the file line by line and search for the key
@@ -419,9 +425,9 @@ function system.getkeyvaluefromfile() {
         fi
     done < "$file_path"
 
-    # Key not found
-    echo ""
-    return 3
+    # Key not found. Return the default value.
+    echo "$default_value"
+    return 1
 }
 
 # Call like system.setkeyvalueinfile "<file-path>" "<key>" "<value>"
@@ -472,6 +478,157 @@ function system.setkeyvalueinfile() {
     }
 
     return 0
+}
+
+# Call like system.deletekeyvaluefromfile "<file-path>" "<key>"
+# - Removes the line matching KEY=* if key exists (match at line start)
+# - Does nothing if key not found
+# - Returns error if file doesn't exist (unless --silent flag is passed)
+function system.deletekeyvaluefromfile() {
+    local file_path="$1"
+    local key="$2"
+    local silent="$3"
+
+    if [ $# -lt 2 ] || string.isemptyorblank "$file_path" || string.isemptyorblank "$key"
+    then
+        echo "Usage: system.deletekeyvaluefromfile <file_path> <key> [--silent]" >&2
+        return 1
+    fi
+
+    if ! system.fileexists "$file_path"
+    then
+        if string.equals "$silent" "--silent" || string.equals "$silent" "-s"
+        then
+            return 0
+        else
+            echo "Error: File '$file_path' does not exist" >&2
+            return 2
+        fi
+    fi
+
+    local temp_file="${file_path}.tmp.$$"
+    local key_found=0
+
+    while IFS= read -r line || [ -n "$line" ]; do
+        if [[ "$line" =~ ^"$key"= ]]; then
+            # Skip this line (don't write it to temp file)
+            key_found=1
+        else
+            echo "$line" >> "$temp_file"
+        fi
+    done < "$file_path"
+
+    # Replace original file with new version
+    mv "$temp_file" "$file_path" || {
+        echo "Error: Failed to update file '$file_path'" >&2
+        rm -f "$temp_file"
+        return 3
+    }
+
+    if [ $key_found -eq 0 ]
+    then
+        return 4  # Key not found
+    fi
+
+    return 0
+}
+
+# Get the canonical (absolute, resolved) path of a file or directory
+# Resolves symlinks and returns an absolute path
+# Expands ~ and environment variables (e.g., $HOME) in the path
+# Works cross-platform (macOS, Linux)
+function system.getcanonicalpath() {
+    local path="$1"
+    
+    if string.isemptyorblank "$path"
+    then
+        echo "" >&2
+        return 1
+    fi
+    
+    # Expand ~ and $HOME in the path
+    # This handles cases where paths are read from files with $HOME or ~
+    # Replace ~ with $HOME first
+    if [[ "$path" == ~/* ]]
+    then
+        path="${path/#~\//$HOME/}"
+    elif [[ "$path" == ~ ]]
+    then
+        path="$HOME"
+    elif [[ "$path" == ~* ]]
+    then
+        # ~username case (less common)
+        path="${path/#~/$HOME}"
+    fi
+    
+    # Expand $HOME variable using simple string replacement (no eval needed!)
+    path="${path//\$HOME/$HOME}"
+    
+    # Try realpath first (available on most modern systems, including macOS with coreutils)
+    if command -v realpath >/dev/null 2>&1
+    then
+        local result
+        result=$(realpath "$path" 2>/dev/null)
+        if [ -n "$result" ]
+        then
+            echo "$result"
+            return 0
+        fi
+    fi
+    
+    # Try readlink -f on Linux (GNU readlink)
+    if readlink -f "$path" >/dev/null 2>&1
+    then
+        local result
+        result=$(readlink -f "$path" 2>/dev/null)
+        if [ -n "$result" ]
+        then
+            echo "$result"
+            return 0
+        fi
+    fi
+    
+    # Fallback: cd + pwd -P approach (works everywhere, including macOS)
+    # pwd -P resolves symlinks (physical path)
+    # This is a standard and reliable cross-platform method
+    local dir_part
+    dir_part=$(dirname "$path")
+    local file_part
+    file_part=$(basename "$path")
+    
+    # Resolve the directory part using cd + pwd -P
+    if [ -d "$dir_part" ] || [ -L "$dir_part" ] || [ -e "$path" ] || [ -L "$path" ]
+    then
+        local resolved_dir
+        resolved_dir=$(cd "$dir_part" 2>/dev/null && pwd -P) || return 1
+        local full_path="$resolved_dir/$file_part"
+        
+        # If the final component is a symlink, try to resolve it
+        if [ -L "$full_path" ]
+        then
+            local link_target
+            link_target=$(readlink "$full_path")
+            if [ "${link_target#/}" != "$link_target" ]
+            then
+                # Absolute symlink - recursively resolve it
+                system.getcanonicalpath "$link_target" && return 0
+            else
+                # Relative symlink - resolve relative to the directory
+                system.getcanonicalpath "$resolved_dir/$link_target" && return 0
+            fi
+        fi
+        
+        echo "$full_path"
+        return 0
+    fi
+    
+    # Last resort: return the path as-is if we can't resolve it
+    echo "$path"
+    return 1
+}
+
+function system.resumeallsuspendedprocesses() {
+  kill -CONT -1
 }
 
 
